- name: Lab 2 tasks
  hosts: G1
  tasks:
  - name: create a group called deploy
    group: name=deploy
  - name: create the user
    user: name=deploy-user group=deploy shell=/bin/bash
  - name: install httpd
    yum: name=httpd state=installed install_weak_deps=yes
  - name: start the httpd service
    service: name=httpd state=started
  - name: create a file called “index.html” in /var/www/html with some dummy html contents
    blockinfile: path=/var/www/html/index.html block='<h1>Welcome to my html page</h1>' create=yes
  - name: install git
    yum: name=git state=installed
  - name: insatall wget
    yum: name=wget state=installed
  - name: clone git repo
    git: repo=https://github.com/scmgalaxy/ansible-role-template dest=/MyRepo
